---
# Create a Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: java-app
---
# Create a Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: java-app
---
# Create a Role with permissions for all resources except nodes
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: java-app
  name: jenkins-role
rules:
- apiGroups: [ "*" ] 
  resources: [ "*" ] 
  verbs: [ "get", "list", "watch", "create", "update", "delete", "patch" ]
---
# Bind the Role to the Service Account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-binding
  namespace: java-app
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: java-app
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
---
# Create a Secret for the Service Account Token
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-sa-token
  namespace: java-app
  annotations:
    kubernetes.io/service-account.name: jenkins-sa
type: kubernetes.io/service-account-token
